\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{HW}[2021/04/22 My Homeworks template]

\LoadClass[a4paper,12pt]{article}

\setlength{\parindent}{0pt}
\setlength{\parskip}{1em}

%% 
%% Copyright © 2015-2018   
%% 
%% Distributable under the LaTeX Project Public License,
%% version 1.3c or higher (your choice). The latest version of
%% this license is at: http://www.latex-project.org/lppl.txt
%% 
%% This work is "maintained" (as per LPPL maintenance status)
%% 
%% 
%% 
%% 
%% 
%% Special thanks to Vafa Khalighi for his invaluable hints.
%%
% End of file `AUT_thesis.cls'.
